////////////////////////////////////////////////////////////////////////
// DO NOT EDIT
// This file was automatically generated by the Impulse C Compiler.
// 
// Impulse C is Copyright 2002-2009, Impulse Accelerated Technologies, Inc.
// 
// Stage Master is Copyright 2002-2009, Green Mountain Computing Systems, Inc.
// 
// All rights reserved.
////////////////////////////////////////////////////////////////////////

module RecognitionArch(
  reset,
  sclk,
  clk,
  p_Producer_output_stream_en,
  p_Producer_output_stream_eos,
  p_Producer_output_stream_data,
  p_Producer_output_stream_rdy,
  p_Consumer_input_stream_en,
  p_Consumer_input_stream_data,
  p_Consumer_input_stream_eos,
  p_Consumer_input_stream_rdy);

  input  reset;
  input  sclk;
  input  clk;
  input  p_Producer_output_stream_en;
  input  p_Producer_output_stream_eos;
  input [31:0] p_Producer_output_stream_data;
  output  p_Producer_output_stream_rdy;
  input  p_Consumer_input_stream_en;
  output [31:0] p_Consumer_input_stream_data;
  output  p_Consumer_input_stream_eos;
  output  p_Consumer_input_stream_rdy;

  wire  p_Recognition_input_stream_rdy;
  wire  p_Recognition_input_stream_en;
  wire  p_Recognition_input_stream_eos;
  wire [31:0] p_Recognition_input_stream_data;
  wire  p_Recognition_output_stream_rdy;
  wire  p_Recognition_output_stream_en;
  wire  p_Recognition_output_stream_eos;
  wire [31:0] p_Recognition_output_stream_data;
  wire  local_reset;

  assign local_reset = reset;

  Recognition Recognition0(
      .reset(local_reset),
      .sclk(sclk),
      .clk(clk),
      .p_input_stream_rdy(p_Recognition_input_stream_rdy),
      .p_input_stream_en(p_Recognition_input_stream_en),
      .p_input_stream_eos(p_Recognition_input_stream_eos),
      .p_input_stream_data(p_Recognition_input_stream_data),
      .p_output_stream_rdy(p_Recognition_output_stream_rdy),
      .p_output_stream_en(p_Recognition_output_stream_en),
      .p_output_stream_eos(p_Recognition_output_stream_eos),
      .p_output_stream_data(p_Recognition_output_stream_data)
    );

  defparam inst0.datawidth = 32;
  defparam inst0.addrwidth = 3;
  stream_dc inst0(
      .ireset(local_reset),
      .iclk(sclk),
      .input_en(p_Producer_output_stream_en),
      .input_rdy(p_Producer_output_stream_rdy),
      .input_eos(p_Producer_output_stream_eos),
      .input_data(p_Producer_output_stream_data),
      .oreset(local_reset),
      .oclk(clk),
      .output_en(p_Recognition_input_stream_en),
      .output_rdy(p_Recognition_input_stream_rdy),
      .output_eos(p_Recognition_input_stream_eos),
      .output_data(p_Recognition_input_stream_data)
    );

  defparam inst1.datawidth = 32;
  defparam inst1.addrwidth = 3;
  stream_dc inst1(
      .ireset(local_reset),
      .iclk(clk),
      .input_en(p_Recognition_output_stream_en),
      .input_rdy(p_Recognition_output_stream_rdy),
      .input_eos(p_Recognition_output_stream_eos),
      .input_data(p_Recognition_output_stream_data),
      .oreset(local_reset),
      .oclk(sclk),
      .output_en(p_Consumer_input_stream_en),
      .output_rdy(p_Consumer_input_stream_rdy),
      .output_eos(p_Consumer_input_stream_eos),
      .output_data(p_Consumer_input_stream_data)
    );

endmodule
