.TH "/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations Directory Reference" 3 "Fri Oct 2 2015" "Facial Recognition - Common Code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmatrixOperations\&.h\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations1\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations2\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations3\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations4\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations5\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrixOperations6\&.c\fP"
.br
.in -1c
