.TH "/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations5.h" 3 "Wed Sep 30 2015" "Facial Recognition - Common Code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations5.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matrixOperations\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_matrix_multiply\fP (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B, int maxCols)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_matrix_division\fP (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_reorder_columns\fP (\fBmatrix_t\fP *M, \fBmatrix_t\fP *V)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBmatrix_t\fP* m_matrix_division (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"

.PP
Definition at line 37 of file matrixOperations5\&.c\&.
.SS "\fBmatrix_t\fP* m_matrix_multiply (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B, intmaxCols)"

.PP
Definition at line 11 of file matrixOperations5\&.c\&.
.SS "\fBmatrix_t\fP* m_reorder_columns (\fBmatrix_t\fP *M, \fBmatrix_t\fP *V)"

.PP
Definition at line 57 of file matrixOperations5\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Facial Recognition - Common Code from the source code\&.
