.TH "/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations4.c" 3 "Fri Oct 2 2015" "Facial Recognition - Common Code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations4.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matrixOperations\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_dot_subtract\fP (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_dot_add\fP (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_dot_division\fP (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBmatrix_t\fP* m_dot_add (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"

.PP
Definition at line 30 of file matrixOperations4\&.c\&.
.SS "\fBmatrix_t\fP* m_dot_division (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"

.PP
Definition at line 48 of file matrixOperations4\&.c\&.
.SS "\fBmatrix_t\fP* m_dot_subtract (\fBmatrix_t\fP *A, \fBmatrix_t\fP *B)"

.PP
Definition at line 12 of file matrixOperations4\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Facial Recognition - Common Code from the source code\&.
