.TH "matrix_t" 3 "Fri Oct 2 2015" "Facial Recognition - Common Code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <matrixOperations\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBprecision\fP * \fBdata\fP"
.br
.ti -1c
.RI "int \fBnumRows\fP"
.br
.ti -1c
.RI "int \fBnumCols\fP"
.br
.ti -1c
.RI "int \fBspan\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file matrixOperations\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBprecision\fP* data"

.PP
Definition at line 31 of file matrixOperations\&.h\&.
.SS "int numCols"

.PP
Definition at line 33 of file matrixOperations\&.h\&.
.SS "int numRows"

.PP
Definition at line 32 of file matrixOperations\&.h\&.
.SS "int span"

.PP
Definition at line 34 of file matrixOperations\&.h\&.
.SS "int type"

.PP
Definition at line 35 of file matrixOperations\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Facial Recognition - Common Code from the source code\&.
