.TH "/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations3.c" 3 "Fri Oct 2 2015" "Facial Recognition - Common Code" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/scott/Clemson-CI---Facial-Recognition/MatrixOperations/matrixOperations3.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'matrixOperations\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBm_inverseMatrix\fP (\fBmatrix_t\fP *M)"
.br
.ti -1c
.RI "\fBprecision\fP \fBm_norm\fP (\fBmatrix_t\fP *M, int specRow)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_sqrtm\fP (\fBmatrix_t\fP *M)"
.br
.ti -1c
.RI "\fBprecision\fP \fBm_determinant\fP (\fBmatrix_t\fP *M)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_cofactor\fP (\fBmatrix_t\fP *M)"
.br
.ti -1c
.RI "\fBmatrix_t\fP * \fBm_covariance\fP (\fBmatrix_t\fP *M)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBmatrix_t\fP* m_cofactor (\fBmatrix_t\fP *M)"

.PP
Definition at line 116 of file matrixOperations3\&.c\&.
.SS "\fBmatrix_t\fP* m_covariance (\fBmatrix_t\fP *M)"

.PP
Definition at line 153 of file matrixOperations3\&.c\&.
.SS "\fBprecision\fP m_determinant (\fBmatrix_t\fP *M)"

.PP
Definition at line 75 of file matrixOperations3\&.c\&.
.SS "void m_inverseMatrix (\fBmatrix_t\fP *M)"

.PP
Definition at line 5 of file matrixOperations3\&.c\&.
.SS "\fBprecision\fP m_norm (\fBmatrix_t\fP *M, intspecRow)"

.PP
Definition at line 29 of file matrixOperations3\&.c\&.
.SS "\fBmatrix_t\fP* m_sqrtm (\fBmatrix_t\fP *M)"

.PP
Definition at line 51 of file matrixOperations3\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Facial Recognition - Common Code from the source code\&.
