#PBS -N feret-knn-dist
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb:gpu_model=k40,walltime=02:00:00

# Accuracy of PCA for several values of knn_dist on the
# FERET dataset, 70/30 partition
if [ $PBS_ENVIRONMENT = "PBS_BATCH" ]; then
	module purge
	module add cuda-toolkit/7.5.18
	module add gcc/4.8.1
	module add git
	module add python/2.7.6

	cd /scratch2/$USER/face-recognition
fi

./scripts/pbs/hyperparameter.sh --gpu -d feret -a pca -p knn_dist > logs/feret-knn-dist.log
