#PBS -N mnist-pca-part
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb,walltime=00:10:00

# Accuracy of PCA across several partitions on the
# MNIST dataset, default hyperparameters
if [ $PBS_ENVIRONMENT = "PBS_BATCH" ]; then
	module purge
	module add cuda-toolkit/7.5.18
	module add gcc/4.8.1
	module add git
	module add python/2.7.6

	cd /scratch2/$USER/face-recognition
fi

./scripts/pbs/partition.sh -d mnist -a pca
