#PBS -N orl-partitions
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb:gpu_model=k40,walltime=00:30:00

# Accuracy of PCA across several partitions on the
# ORL dataset, default hyperparameters
if [ $PBS_ENVIRONMENT = "PBS_BATCH" ]; then
	module purge
	module add cuda-toolkit/7.5.18
	module add gcc/4.8.1
	module add git
	module add python/2.7.6

	cd /scratch2/$USER/face-recognition
fi

./scripts/pbs/partition.sh -d orl -a pca
