#PBS -N orl-pca-lda-ica
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb,walltime=00:10:00

# Accuracy of PCA, LDA, and ICA on the ORL dataset,
# 70/30 partition

DATASET=orl
TRAIN=70
TEST=30
NUM_ITER=3

module purge
module add cuda-toolkit/7.5.18
module add gcc/4.8.1
module add git
module add python/2.7.6

cd /scratch2/$USER/face-recognition

for A in "pca" "lda" "ica"; do
	echo "Testing $A"
	python ./scripts/cross-validate.py --run-c -d $DATASET -t $TRAIN -r $TEST -i $NUM_ITER --$A
done 
