#PBS -N orl-ica-n2
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb,walltime=00:10:00

# Accuracy of ICA across several values of ica_n2 on the
# ORL dataset, 70/30 partition
if [ $PBS_ENVIRONMENT = "PBS_BATCH" ]; then
	module purge
	module add cuda-toolkit/7.5.18
	module add gcc/4.8.1
	module add git
	module add python/2.7.6

	cd /scratch2/$USER/face-recognition
fi

./scripts/pbs/hyperparameter.sh -d orl -a ica -p ica_n2
