#PBS -N orl-pca-lda-ica
#PBS -l select=1:ncpus=8:ngpus=1:mem=8gb,walltime=00:10:00

# Accuracy of PCA, LDA, and ICA on the ORL dataset

DATASET=orl
NUM_ITER=5
NUM_TEST=1

module purge
module add cuda-toolkit/7.5.18
module add gcc/4.8.1
module add git
module add python/2.7.6

cd /scratch2/$USER/face-recognition

ALGORITHMS=(pca lda ica)
for A in "${ALGORITHMS[@]}"; do
	echo $A
	python ./scripts/cross-validate.py --run-c -d $DATASET -r $NUM_TEST -i $NUM_ITER --$A
done 
